{% set name = "aiochclient" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c678a84b615a1023de533cbb669a283563563930eaa9b667e3829d3e8f15dfa

build:
  number: 1
  skip: true  # [win]
  skip: true  # [py<36]
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - aiohttp >=3.0.1
    - sqlparse >=0.3.0
    - python
    - ciso8601  # [py<37]

test:
  imports:
    - aiochclient
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/maximdanilchenko/aiochclient
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Async http clickhouse client for python 3.6+
  doc_url: https://aiochclient.readthedocs.io/

extra:
  recipe-maintainers:
    - xhochy
