{% set name = "aiochclient" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 839defc0e5222a6e07efabc88de39488baf2c827298ae8a8bfb3fc344c0f39aa

build:
  number: 0
  skip: true  # [win]
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - pip
    - python
    - setuptools
  run:
    - aiohttp >=3.0.1
    - sqlparse >=0.3.0
    - python

test:
  imports:
    - aiochclient
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/maximdanilchenko/aiochclient
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Async http clickhouse client for python 3.6+
  doc_url: https://aiochclient.readthedocs.io/

extra:
  recipe-maintainers:
    - xhochy
