travis:
  secure:
    BINSTAR_TOKEN: iFOgfJNS9JGosJsgss4y8BDCBVxjpqriq2+eYhhR+CT5QNQNKPDlYP5pfOf5arQHVKbpJ7bVEKc1+1oF/wC0BN60Cb1sHU+m3AIxPv4PtHwnEnFuLjQlHuOJHzspO1Lkvuu+fdowlkA1nX0U+HU7KIHO78E8Q3uPxgFOKULXDz1sU6kJtzFbJb/6bEwIE4tEHcnCMevTS2YhICczf0/h/l/IjCaRn9aBSBzOrMm9QKRqPUpA6k1u5ZB/UylPeXob54rvWyQdi3izw1Ijj5dPXAYAF3pENDnS0gOrUI1wfIKhOe1YEp4Aq1wcKT1g3ApyzBEHRgXTne2XT/qz3QvS1Mw8cIxASKjXM/tzQWKGxhCZVXP1jxXZnqlJPO7MtcC09MoFjRc4aVGoFfWrtkrTVUZLjTSrwFwmAJYtI3RDyYfNSF6zoWB1B3x0ilPpyno40pcmcvDtnKDtDOjfMjOfTcY+4YrUuFe5n5YwdDhssN/9dL6lvrw3zH9dWMzLveCE3WypdF+1ddP/u2C3J3ihlMz9qEa7vLv+Ecl9z/PfArkuhrSs1Ad5Hmoxd3gH51e0XFNdbGD4DaxFLSN8dVFjrJM3LVYui7EZO63kh/9JutL2DFcsAeV+WrE6K7vY/kUvZm7xRzklYU2xjKNthn31MqOjidW/hFnS8+NTFcSKIZw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
